(in-package :6502-cpu)

(setf (gethash #x01 instructions) #'ora)
(setf (gethash #x21 instructions) #'anda)
; (setf (gethash #x24 instructions) #'bit)
; (setf (gethash #x2C instructions) #'bit)
(setf (gethash #x78 instructions) #'sei)
(setf (gethash #x80 instructions) #'sty)
(setf (gethash #x81 instructions) #'sta)
(setf (gethash #x82 instructions) #'stx)
(setf (gethash #x8A instructions) #'txa)
(setf (gethash #x88 instructions) #'dey)
(setf (gethash #x9A instructions) #'txs)
(setf (gethash #xA0 instructions) #'ldy)
(setf (gethash #xA1 instructions) #'lda)
(setf (gethash #xA2 instructions) #'ldx)
(setf (gethash #xC1 instructions) #'cmp)
(setf (gethash #xCA instructions) #'dex)
(setf (gethash #xC0 instructions) #'cpy)
(setf (gethash #xC8 instructions) #'iny)
(setf (gethash #xD8 instructions) #'cld)
(setf (gethash #xE0 instructions) #'cpx)
(setf (gethash #xE2 instructions) #'inc)
